version: '3.8'

services:
  backend:
    build:
      context: . # Assurez-vous que ce chemin existe et pointe vers le bon dossier
      dockerfile: Dockerfile-test
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .  # Assurez-vous que ce chemin existe également
      dockerfile: Dockerfile-test-fe
    ports:
      - "3000:3000"
