version: '3.8'

services:
  backend:
    build:
      context: . # Assurez-vous que ce chemin existe et pointe vers le bon dossier
      dockerfile: ./app/backend/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: . # Assurez-vous que ce chemin existe également
      dockerfile: ./app/frontend/Dockerfile
    ports:
      - "3000:3000"
