version: '3.8'

services:
  backend:
    build:
      context: ./app/backend  # Assurez-vous que ce chemin existe et pointe vers le bon dossier
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./app/frontend  # Assurez-vous que ce chemin existe également
    ports:
      - "3000:3000"
