name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Se connecter à DockerHub avec un token
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Étape 3 : Construire et pousser l'image du backend
      - name: Build and push backend image
        run: |
          cd app/backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Étape 4 : Construire et pousser l'image du frontend
      - name: Build and push frontend image
        run: |
          cd app/frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  deploy-to-cloud:
    name: Deploy to Cloud Platform
    needs: build-and-push-docker-images
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Déployer sur la plateforme cloud (Railway, Koyeb, etc.)
      - name: Deploy to cloud platform
        run: |
          echo "Add deployment commands here for your chosen cloud platform."
